name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake (Windows)
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64
      if: runner.os == 'Windows'

    - name: Configure CMake (non-Windows)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      if: runner.os != 'Windows'

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config Release
